[package]
name = "rust-practice"
version = "0.1.0"
authors = ["ka_ueno <ka.ueno@acca-int.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
